import { IProject } from "../helpers/types";

const WALLETS: IProject[] = [
  {
    name: "Rainbow",
    icon: require("../assets/wallets/rainbow.png"),
    url: "https://rainbow.me/",
    style: {},
  },
  {
    name: "Trust",
    icon: require("../assets/wallets/trust-wallet.png"),
    url: "https://trustwallet.com/",
    style: {},
  },
  {
    name: "Argent",
    icon: require("../assets/wallets/argent.jpg"),
    url: "https://www.argent.xyz/",
    style: {},
  },
  {
    name: "Metamask",
    icon: require("../assets/wallets/metamask.png"),
    url: "https://mobile.metamask.io/",
    style: {},
  },
  {
    name: "Gnosis Safe Multisig",
    icon: require("../assets/wallets/gnosis-safe.jpg"),
    url: "https://gnosis-safe.io/",
    style: {},
  },
  {
    name: "Crypto.com | DeFi Wallet",
    icon: require("../assets/wallets/crypto.png"),
    url: "https://crypto.com/en/defi/wallet/",
    style: {},
  },
  {
    name: "Pillar",
    icon: require("../assets/wallets/pillar-wallet.png"),
    url: "https://pillarproject.io/",
    style: { cropCircle: true },
  },
  {
    name: "imToken",
    icon: require("../assets/wallets/imtoken.png"),
    url: "https://token.im/",
    style: {},
  },
  {
    name: "TokenPocket",
    icon: require("../assets/wallets/tokenpocket.png"),
    url: "https://www.tokenpocket.pro/",
    style: { cropCircle: true },
  },
  {
    name: "Walleth",
    icon: require("../assets/wallets/walleth.png"),
    url: "https://walleth.org/",
    style: {},
  },
  {
    name: "Atomic",
    icon: require("../assets/wallets/atomic.png"),
    url: "https://atomicwallet.io/",
    style: {},
  },
  {
    name: "Authereum",
    icon: require("../assets/wallets/authereum.png"),
    url: "https://authereum.org",
    style: {},
  },
  {
    name: "Huobi Wallet",
    icon: require("../assets/wallets/huobi.jpg"),
    url: "https://www.huobiwallet.com/",
    style: { cropCircle: true },
  },
  {
    name: "Eidoo",
    icon: require("../assets/wallets/eidoo.png"),
    url: "https://eidoo.io/",
    style: {},
  },
  {
    name: "ZelCore",
    icon: require("../assets/wallets/zelcore.png"),
    url: "https://zel.network/project/zelcore/",
    style: {},
  },
  {
    name: "Nash",
    icon: require("../assets/wallets/nash.jpg"),
    url: "https://nash.io/",
    style: { cropCircle: true },
  },
  {
    name: "Coinomi",
    icon: require("../assets/wallets/coinomi.jpg"),
    url: "https://coinomi.com/",
    style: { cropCircle: true },
  },
  {
    name: "GridPlus",
    icon: require("../assets/wallets/gridplus.png"),
    url: "https://gridplus.io/",
    style: {},
  },
  {
    name: "CoolWallet S",
    icon: require("../assets/wallets/coolwallet-s.png"),
    url: "https://www.coolwallet.io/",
    style: {},
  },
  {
    name: "Alice",
    icon: require("../assets/wallets/alice.png"),
    url: "https://www.alicedapp.com/",
    style: { cropCircle: true },
  },
  {
    name: "Alpha",
    icon: require("../assets/wallets/alpha-wallet.jpg"),
    url: "https://alphawallet.com/",
    style: { cropCircle: true },
  },
  {
    name: "Tokenary",
    icon: require("../assets/wallets/tokenary.png"),
    url: "https://tokenary.io/",
    style: {},
  },
  {
    name: "SafePal",
    icon: require("../assets/wallets/safepal.png"),
    url: "https://safepal.io/",
    style: {},
  },
  {
    name: "Equal",
    icon: require("../assets/wallets/equal.jpg"),
    url: "https://equal.tech/",
    style: {},
  },
  {
    name: "Infinito",
    icon: require("../assets/wallets/infinito-wallet.png"),
    url: "https://www.infinitowallet.io/",
    style: {},
  },
  {
    name: "MathWallet",
    icon: require("../assets/wallets/math-wallet.png"),
    url: "https://mathwallet.org/en/",
    style: {},
  },
  {
    name: "MYKEY",
    icon: require("../assets/wallets/mykey.png"),
    url: "https://mykey.org",
    style: {},
  },
  {
    name: "Spatium",
    icon: require("../assets/wallets/spatium.jpg"),
    url: "https://spatium.net/",
    style: { cropCircle: true },
  },
  {
    name: "wallet.io",
    icon: require("../assets/wallets/wallet.io.png"),
    url: "https://wallet.io/",
    style: {},
  },
  {
    name: "Infinity Wallet",
    icon: require("../assets/wallets/infinity-wallet.png"),
    url: "https://infinitywallet.io/",
    style: {},
  },
  {
    name: "Ownbit",
    icon: require("../assets/wallets/ownbit.png"),
    url: "https://ownbit.io/",
    style: {},
  },
  {
    name: "EasyPocket",
    icon: require("../assets/wallets/easypocket.jpg"),
    url: "https://easypocket.app/",
    style: {},
  },
  {
    name: "ONTO",
    icon: require("../assets/wallets/onto.png"),
    url: "https://onto.app/",
    style: {},
  },
  {
    name: "Bridge Wallet",
    icon: require("../assets/wallets/bridge.png"),
    url: "https://www.mtpelerin.com/bridge-wallet",
    style: {},
  },
  {
    name: "SparkPoint",
    icon: require("../assets/wallets/sparkpoint.png"),
    url: "https://sparkpoint.io/",
    style: {},
  },
  {
    name: "ViaWallet",
    icon: require("../assets/wallets/viawallet.png"),
    url: "https://viawallet.com/",
    style: {},
  },
  {
    name: "Coin98",
    icon: require("../assets/wallets/coin98.png"),
    url: "https://coin98.app/",
    style: {},
  },
  {
    name: "BitKeep",
    icon: require("../assets/wallets/bitkeep.png"),
    url: "https://bitkeep.com/",
    style: {},
  },
  {
    name: "Vision",
    icon: require("../assets/wallets/vision.png"),
    url: "https://vision-crypto.com/",
    style: {},
  },
  {
    name: "SWFT Wallet",
    icon: require("../assets/wallets/swft.png"),
    url: "https://www.swft.pro/",
    style: {},
  },
  {
    name: "PeakDeFi Wallet",
    icon: require("../assets/wallets/peakdefi.png"),
    url: "https://app.peakdefi.com/download",
    style: {},
  },
  {
    name: "XDC Wallet",
    icon: require("../assets/wallets/xdc.png"),
    url: "https://play.google.com/store/apps/details?id=com.xdcwallet",
    style: {},
  },
  {
    name: "Unstoppable Wallet",
    icon: require("../assets/wallets/unstoppable.png"),
    url: "https://unstoppable.money/",
    style: {},
  },
  {
    name: "MEET.ONE",
    icon: require("../assets/wallets/meetone.jpg"),
    url: "https://meet.one/",
    style: {},
  },
  {
    name: "Dok Wallet",
    icon: require("../assets/wallets/dok.png"),
    url: "https://dokwallet.com/",
    style: {},
  },
  {
    name: "AT.Wallet",
    icon: require("../assets/wallets/atwallet.png"),
    url: "https://authentrend.com/at-wallet/",
    style: {},
  },
  {
    name: "MoriX Wallet",
    icon: require("../assets/wallets/morixwallet.png"),
    url: "https://morixjp.com/product/walletcard",
    style: {},
  },
];

export default WALLETS;
