export const GITHUB_URL = 'https://github.walletconnect.org/';
export const DOCS_URL = 'https://docs.walletconnect.org/';
export const WALLETS_URL = '/wallets';
export const APPS_URL = '/apps';
export const WEB3MODAL_URL = 'https://github.com/Web3Modal/web3modal';
export const WEB3_QUICKSTART_URL = 'https://docs.walletconnect.org/quick-start/dapps/web3-provider';
export const DISCORD_URL = 'https://discord.gg/jhxMvxP';
export const TWITTER_URL = 'https://twitter.walletconnect.org/';
export const WALLETS_API_URL = 'https://registry.walletconnect.org/data/wallets.json';
export const APPS_API_URL = 'https://registry.walletconnect.org/data/dapps.json';
export const IMG_API_URL = 'https://registry.walletconnect.org/logo/lg/'
export const TIME_TO_REVALIDATION = 10 * 60 * 60; //minutes